# Generated by Django 6.1.1 on 2026-09-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('policy_id', models.CharField(max_length=64)),
                ('policy_start_date', models.CharField(max_length=32)),
                ('filed_date', models.CharField(max_length=32)),
                ('claimant_name', models.CharField(max_length=200)),
                ('claimant_gender', models.CharField(max_length=32)),
                ('claimant_city', models.CharField(max_length=200)),
                ('narrative_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('done', 'Done')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='decision', serialize=False, to='claims.claim')),
                ('outcome', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('confidence', models.FloatField()),
                ('escalation_reason', models.TextField(blank=True, null=True)),
                ('ui_spec', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('node', models.CharField(max_length=64)),
                ('detail', models.TextField()),
                ('occurred_at', models.CharField(max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='claims.claim')),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
            },
        ),
    ]
